#!/usr/bin/env python3
"""
Ran_Type_LCD 用 音声→C配列変換ツール

BGM: int16_t PCM, 16000Hz の配列を生成します。
  sound.cpp の BEACH_BGM / BONFIRE_BGM / RAIN_BGM と同じ形式で出力します。

使い方:
  python tool/audio_to_carray.py input.wav -o output.c -n ARRAY_NAME
  python tool/audio_to_carray.py input.wav -o output.c -n MY_BGM --max-samples 64 --rate 16000

# 例: sea.wav を 16000 Hz の BGM 用配列にし、先頭 64 サンプルだけ my_bgm.c に出力
　python tool/audio_to_carray.py sea.wav -o my_bgm.c -n SEA_BGM -r 16000 -m 64
"""

import argparse
import sys
import wave


def load_wav(path: str):
    """WAVを読み、モノラル int16 サンプルリストとサンプルレートを返す。"""
    with wave.open(path, "rb") as w:
        nch = w.getnchannels()
        sampwidth = w.getsampwidth()
        framerate = w.getframerate()
        nframes = w.getnframes()
        raw = w.readframes(nframes)

    if sampwidth == 2:  # 16bit
        import struct
        fmt = "<" + ("h" * (len(raw) // 2))
        samples = list(struct.unpack(fmt, raw))
    else:
        raise ValueError(f"Unsupported WAV bit depth: {sampwidth} bytes (use 16-bit)")

    if nch == 2:
        samples = [samples[i] for i in range(0, len(samples), 2)]
    elif nch != 1:
        raise ValueError(f"Unsupported channels: {nch} (use mono or stereo)")

    return samples, framerate


def resample(samples: list, from_rate: int, to_rate: int) -> list:
    """線形補間でリサンプル。"""
    if from_rate == to_rate:
        return samples
    out_len = int(len(samples) * to_rate / from_rate)
    out = []
    for i in range(out_len):
        pos = i * from_rate / to_rate
        idx = int(pos)
        frac = pos - idx
        if idx >= len(samples) - 1:
            out.append(samples[-1])
        else:
            a, b = samples[idx], samples[idx + 1]
            out.append(int(a + (b - a) * frac))
    return out


def clamp_s16(x: int) -> int:
    if x > 32767:
        return 32767
    if x < -32768:
        return -32768
    return x


def format_c_array(samples: list, name: str, values_per_line: int = 8) -> str:
    """int16 サンプルを C の static const int16_t NAME[] = { ... }; 形式にする。"""
    lines = [f"static const int16_t {name}[{len(samples)}] = {{"]
    for i in range(0, len(samples), values_per_line):
        chunk = samples[i : i + values_per_line]
        line = "    " + ", ".join(str(clamp_s16(s)) for s in chunk)
        if i + len(chunk) < len(samples):
            line += ","
        lines.append(line)
    lines.append("};")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="WAV を Ran_Type_LCD 用の int16_t C 配列に変換する"
    )
    parser.add_argument("input", help="入力 WAV ファイル（16bit, モノ/ステレオ）")
    parser.add_argument("-o", "--output", default=None, help="出力 .c ファイル（省略時は標準出力）")
    parser.add_argument("-n", "--name", default="AUDIO_SAMPLES", help="C 配列の名前")
    parser.add_argument("-r", "--rate", type=int, default=16000, help="出力サンプルレート (Hz)")
    parser.add_argument(
        "-m", "--max-samples",
        type=int,
        default=0,
        help="最大サンプル数（0=全て）。BGM ループ用に 64 などにすると短くできる"
    )
    parser.add_argument(
        "--values-per-line",
        type=int,
        default=8,
        help="C 配列の1行あたりの値の数"
    )
    args = parser.parse_args()

    try:
        samples, in_rate = load_wav(args.input)
    except Exception as e:
        print(f"Error loading WAV: {e}", file=sys.stderr)
        return 1

    if args.rate != in_rate:
        samples = resample(samples, in_rate, args.rate)

    if args.max_samples > 0 and len(samples) > args.max_samples:
        samples = samples[: args.max_samples]

    text = format_c_array(samples, args.name, args.values_per_line)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write("/* Generated by tool/audio_to_carray.py */\n")
            f.write(f"/* Source: {args.input}, rate={args.rate}, samples={len(samples)} */\n\n")
            f.write(text)
            f.write("\n")
        print(f"Wrote {args.output} ({len(samples)} samples)", file=sys.stderr)
    else:
        print("/* Generated by tool/audio_to_carray.py */")
        print(text)

    return 0


if __name__ == "__main__":
    sys.exit(main())
